### ISSUE TITLE
About translations

### ISSUE THREAD

**Issue by aleen42** [github/open-source-guide#322] opened 2017-02-21 16:36 UTC
Hello, I am a front-end developer from China, and I have always translated some articles into Chinese. Here I have found that this open source guides can be deliver widely by translating them into different languages. However, is there any guideline for this translating? For instance, to create a plan for translation and provide a apparent list of guides contributed by others with issues, so that we can easily grasp what we can translate.

Sincerely yours, aleen42.

**Comment by lee-dohm** [comment] 2017-02-21 16:44
Investigation into providing translations and creating guidelines is ongoing in #295 and #299. You may want to subscribe there for updates. Since this request is a duplicate of those, I'm going to close this one.

Thanks for reaching out and offering to help!

**Closed by lee-dohm** 2017-02-21 16:44 UTC
